config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: 'customers#index'
  resources :customers, only: [:index] do
    collection do
      get :alphabetized
      get :missing_email
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
def self.ransackable_attributes(auth_object = nil)
       ["created_at", "email", "id", "updated_at"]
end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image
  validates :full_name, :email, presence: true
  validates :email, uniqueness: true
  validates :phone_number, presence: true, length: { maximum: 12 }
  validates :notes, length: { maximum: 500 }

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "full_name", "id", "notes", "phone_number", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["image_attachment", "image_blob"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(email: [nil, ''])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="column">
  <div class="card">
      <div class="card-content">
        <% if customer.image.present? %>
        <div class="card-image">
          <figure class="image is-64x64">
            <%= image_tag customer.image %>
          </figure>
        </div>
        <% end %>
      </div>
      <div class="ml-4">
      <footer class="card-footer">
        <h3 class="card-footer-item subtitle"><%= customer.full_name %></h3>
        <p class="card-footer-item subtitle"><%= customer.email %></p>
        <p class="card-footer-item subtitle"><%= customer.phone_number %></p>
      </footer>
    </div>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<h1 class="title is-3 mt-4 mx-4 has-text-black">All Customers in Alphabetized Order</h1>

<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>

app/views/customers/index.html.erb
<h1 class="title is-3 mt-4 mx-4 has-text-black">All Customers</h1>

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-item">
    <%= link_to 'All Customers', customers_path %> |
    <%= link_to 'Alphabetized Customers', alphabetized_customers_path %> |
    <%= link_to 'Customers Missing Email', missing_email_customers_path %>
  </div>
</nav>

<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>

app/views/customers/missing_email.html.erb
<h1 class="title is-3 mt-4 mx-4 has-text-black">All Customers with Missing Email</h1>

<% @customers.each do |customer| %>
  <%= render partial: 'customer', locals: { customer: customer } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "U6 Challenge" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@1.0.2/css/bulma.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>